# Generated by Django 4.0.6 on 2024-11-30 07:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='investor/company_logos/')),
                ('sector', models.CharField(max_length=100)),
                ('stage', models.CharField(max_length=50)),
                ('investment_date', models.DateField()),
                ('investment_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ownership', models.CharField(max_length=10)),
                ('valuation', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InvestorFinancialMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('cash_balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('gross_burn', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ebitda', models.DecimalField(decimal_places=2, max_digits=20)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='InvestorFundingRound',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('round_type', models.CharField(max_length=50)),
                ('amount_raised', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='InvestorGrowthMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('new_customers', models.PositiveIntegerField()),
                ('churned_customers', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='InvestorPerformanceMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('growth', models.DecimalField(decimal_places=2, max_digits=5)),
                ('trend', models.CharField(max_length=10)),
                ('revenue_change', models.CharField(max_length=10)),
                ('user_growth', models.CharField(max_length=10)),
                ('margin', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Investor Performance Metrics',
            },
        ),
        migrations.CreateModel(
            name='InvestorPortfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_companies', models.PositiveIntegerField()),
                ('active_investments', models.PositiveIntegerField()),
                ('exits', models.PositiveIntegerField()),
                ('irr', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'Investor Portfolios',
            },
        ),
        migrations.CreateModel(
            name='InvestorTeamGrowth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('department', models.CharField(max_length=100)),
                ('headcount', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.RenameModel(
            old_name='ComplianceDocument',
            new_name='InvestorComplianceDocument',
        ),
        migrations.RenameModel(
            old_name='Expertise',
            new_name='InvestorExpertise',
        ),
        migrations.RenameModel(
            old_name='InvestmentPreference',
            new_name='InvestorInvestmentPreference',
        ),
        migrations.RemoveIndex(
            model_name='investorcompliancedocument',
            name='api_complia_investo_963102_idx',
        ),
        migrations.RemoveIndex(
            model_name='investorcompliancedocument',
            name='api_complia_uploade_6bf9c6_idx',
        ),
        migrations.AddIndex(
            model_name='investorcompliancedocument',
            index=models.Index(fields=['investor', 'document_type'], name='api_investo_investo_cb4afe_idx'),
        ),
        migrations.AddIndex(
            model_name='investorcompliancedocument',
            index=models.Index(fields=['uploaded_at'], name='api_investo_uploade_e79189_idx'),
        ),
        migrations.AddField(
            model_name='investorteamgrowth',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_growth', to='api.investor'),
        ),
        migrations.AddField(
            model_name='investorportfolio',
            name='investor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='api.investor'),
        ),
        migrations.AddField(
            model_name='investorperformancemetric',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metric', to='api.investorcompany'),
        ),
        migrations.AddField(
            model_name='investorgrowthmetric',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_metrics', to='api.investor'),
        ),
        migrations.AddField(
            model_name='investorfundinground',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_rounds', to='api.investor'),
        ),
        migrations.AddField(
            model_name='investorfinancialmetric',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_metrics', to='api.investor'),
        ),
        migrations.AddField(
            model_name='investorcompany',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='api.investorportfolio'),
        ),
        migrations.AlterUniqueTogether(
            name='investorteamgrowth',
            unique_together={('investor', 'department', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='investorgrowthmetric',
            unique_together={('investor', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='investorfundinground',
            unique_together={('investor', 'round_type', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='investorfinancialmetric',
            unique_together={('investor', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='investorcompany',
            unique_together={('portfolio', 'name')},
        ),
    ]
