# Generated by Django 4.0.6 on 2024-11-30 12:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_investorcompany_investorfinancialmetric_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('logo', models.ImageField(upload_to='investor/company_logos/')),
                ('sector', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('returns', models.DecimalField(decimal_places=2, max_digits=5)),
                ('investment_date', models.DateField()),
                ('founded_year', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=255)),
                ('employee_count', models.PositiveIntegerField()),
                ('funding_round', models.CharField(max_length=50)),
                ('market_share', models.DecimalField(decimal_places=2, max_digits=5)),
                ('growth_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('customer_retention', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ltv', models.DecimalField(decimal_places=2, max_digits=10)),
                ('market_position', models.CharField(max_length=100)),
                ('target_market_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('market_growth_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('geographic_presence', models.JSONField(default=list)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_companies', to='api.investor')),
            ],
            options={
                'ordering': ['-investment_date'],
                'unique_together': {('investor', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RiskData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_data', to='api.investmentcompany')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('projection', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_data', to='api.investmentcompany')),
            ],
        ),
    ]
