# Generated by Django 4.2.16 on 2024-12-05 03:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_investmentcompany_riskdata_performancedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('logo', models.ImageField(upload_to='startups/logos/')),
                ('engagement_level', models.CharField(choices=[('EXPLORER', 'Explorer'), ('GROWTH', 'Growth'), ('SCALE', 'Scale'), ('MATURE', 'Mature')], max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('website', models.URLField(blank=True)),
                ('founded_date', models.DateField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('years_of_experience', models.PositiveIntegerField()),
                ('team_size', models.PositiveIntegerField()),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=20)),
                ('patents_filed', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StartupStageValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stage', models.CharField(max_length=50)),
                ('market_validation_status', models.CharField(max_length=50)),
                ('product_validation_status', models.CharField(max_length=50)),
                ('startup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stage_validation', to='api.startup')),
            ],
        ),
        migrations.CreateModel(
            name='StartupServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_areas', to='api.startup')),
            ],
        ),
        migrations.CreateModel(
            name='StartupMarketPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operations_type', models.CharField(max_length=100)),
                ('international_markets', models.PositiveIntegerField()),
                ('active_customers', models.PositiveIntegerField()),
                ('startup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='market_presence', to='api.startup')),
            ],
        ),
        migrations.CreateModel(
            name='StartupIndustryFocus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=100)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industry_focuses', to='api.startup')),
            ],
        ),
        migrations.CreateModel(
            name='StartupAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('proof_document', models.FileField(blank=True, null=True, upload_to='startups/achievements/')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='api.startup')),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.AddIndex(
            model_name='startup',
            index=models.Index(fields=['name'], name='api_startup_name_96810f_idx'),
        ),
        migrations.AddIndex(
            model_name='startup',
            index=models.Index(fields=['engagement_level'], name='api_startup_engagem_c88d65_idx'),
        ),
        migrations.AddIndex(
            model_name='startup',
            index=models.Index(fields=['city', 'state'], name='api_startup_city_51170a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='startupservicearea',
            unique_together={('startup', 'service')},
        ),
        migrations.AlterUniqueTogether(
            name='startupindustryfocus',
            unique_together={('startup', 'industry')},
        ),
    ]
