# Generated by Django 4.2.16 on 2024-12-05 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_startup_startupstagevalidation_startupservicearea_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupMetricsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('current_growth_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('current_monthly_revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_active_users', models.PositiveIntegerField()),
                ('current_market_share', models.DecimalField(decimal_places=2, max_digits=5)),
                ('startup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_metrics', to='api.startup')),
            ],
        ),
        migrations.CreateModel(
            name='StartupMetricTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField()),
                ('metric_type', models.CharField(choices=[('GROWTH', 'Growth Rate'), ('REVENUE', 'Revenue'), ('USERS', 'User Base'), ('MARKET', 'Market Share')], max_length=20)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('achieved', models.BooleanField(default=False)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_targets', to='api.startup')),
            ],
            options={
                'ordering': ['target_date'],
                'unique_together': {('startup', 'metric_type', 'target_date')},
            },
        ),
        migrations.CreateModel(
            name='StartupMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('growth_rate', models.DecimalField(decimal_places=2, help_text='Monthly growth rate in percentage', max_digits=5)),
                ('growth_rate_trend', models.DecimalField(decimal_places=2, help_text='Change in growth rate vs previous month', max_digits=5)),
                ('monthly_revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('revenue_trend', models.DecimalField(decimal_places=2, help_text='Change in revenue vs previous month', max_digits=5)),
                ('active_users', models.PositiveIntegerField()),
                ('user_growth_trend', models.DecimalField(decimal_places=2, help_text='Change in user base vs previous month', max_digits=5)),
                ('market_share', models.DecimalField(decimal_places=2, help_text='Market share percentage', max_digits=5)),
                ('market_share_trend', models.DecimalField(decimal_places=2, help_text='Change in market share vs previous month', max_digits=5)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='api.startup')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['startup', 'date'], name='api_startup_startup_b915ba_idx'), models.Index(fields=['date'], name='api_startup_date_93e426_idx')],
                'unique_together': {('startup', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StartupMetricAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('POSITIVE', 'Positive Change'), ('NEGATIVE', 'Negative Change'), ('TARGET_REACHED', 'Target Reached'), ('THRESHOLD_BREACH', 'Threshold Breach')], max_length=20)),
                ('metric_type', models.CharField(choices=[('GROWTH', 'Growth Rate'), ('REVENUE', 'Revenue'), ('USERS', 'User Base'), ('MARKET', 'Market Share')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_alerts', to='api.startup')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['startup', 'created_at'], name='api_startup_startup_058b9b_idx'), models.Index(fields=['alert_type'], name='api_startup_alert_t_716df5_idx')],
            },
        ),
    ]
