# Generated by Django 4.2.16 on 2024-12-09 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_scheme_schemeeligibilitycriteria_schemedetail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue_model', models.CharField(max_length=100)),
                ('funding_rounds', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='StartupBasicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='startup_logos/')),
                ('tagline', models.CharField(max_length=200)),
                ('founded', models.CharField(max_length=4)),
                ('type', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('registration', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('website', models.URLField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('linkedin', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='StartupMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=50)),
                ('gradient', models.CharField(max_length=100)),
                ('growth', models.CharField(max_length=50)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='api.startupbasicinfo')),
            ],
        ),
        migrations.CreateModel(
            name='StartupProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('features', models.JSONField()),
                ('target_audience', models.CharField(max_length=200)),
                ('launch_date', models.CharField(max_length=4)),
                ('demo_link', models.URLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.startupbasicinfo')),
            ],
        ),
        migrations.CreateModel(
            name='StartupVisionMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision', models.TextField()),
                ('mission', models.TextField()),
                ('values', models.JSONField()),
                ('startup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vision_mission', to='api.startupbasicinfo')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='team_images/')),
                ('bio', models.TextField()),
                ('linkedin', models.URLField()),
                ('skills', models.JSONField()),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='api.startupbasicinfo')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='schemeapplication',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='schemeapplication',
            name='scheme',
        ),
        migrations.RemoveField(
            model_name='schemeapplication',
            name='startup',
        ),
        migrations.RemoveField(
            model_name='schemedetail',
            name='scheme',
        ),
        migrations.RemoveField(
            model_name='schemeeligibilitycriteria',
            name='scheme',
        ),
        migrations.RemoveField(
            model_name='startupachievement',
            name='startup',
        ),
        migrations.AlterUniqueTogether(
            name='startupindustryfocus',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='startupindustryfocus',
            name='startup',
        ),
        migrations.RemoveField(
            model_name='startupmarketpresence',
            name='startup',
        ),
        migrations.RemoveField(
            model_name='startupmetricalert',
            name='startup',
        ),
        migrations.AlterUniqueTogether(
            name='startupmetrics',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='startupmetrics',
            name='startup',
        ),
        migrations.RemoveField(
            model_name='startupmetricssnapshot',
            name='startup',
        ),
        migrations.AlterUniqueTogether(
            name='startupmetrictarget',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='startupmetrictarget',
            name='startup',
        ),
        migrations.AlterUniqueTogether(
            name='startupservicearea',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='startupservicearea',
            name='startup',
        ),
        migrations.RemoveField(
            model_name='startupstagevalidation',
            name='startup',
        ),
        migrations.DeleteModel(
            name='Scheme',
        ),
        migrations.DeleteModel(
            name='SchemeApplication',
        ),
        migrations.DeleteModel(
            name='SchemeDetail',
        ),
        migrations.DeleteModel(
            name='SchemeEligibilityCriteria',
        ),
        migrations.DeleteModel(
            name='Startup',
        ),
        migrations.DeleteModel(
            name='StartupAchievement',
        ),
        migrations.DeleteModel(
            name='StartupIndustryFocus',
        ),
        migrations.DeleteModel(
            name='StartupMarketPresence',
        ),
        migrations.DeleteModel(
            name='StartupMetricAlert',
        ),
        migrations.DeleteModel(
            name='StartupMetrics',
        ),
        migrations.DeleteModel(
            name='StartupMetricsSnapshot',
        ),
        migrations.DeleteModel(
            name='StartupMetricTarget',
        ),
        migrations.DeleteModel(
            name='StartupServiceArea',
        ),
        migrations.DeleteModel(
            name='StartupStageValidation',
        ),
        migrations.AddField(
            model_name='financial',
            name='startup',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financials', to='api.startupbasicinfo'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='api.startupbasicinfo'),
        ),
    ]
